name: 删除多个账号指定区域所有SAP应用

on:
  workflow_dispatch:
    inputs:
      region:
        description: '选择要删除应用的区域 (SG 或 US)'
        required: true
        default: 'SG'
        type: choice
        options:
          - SG
          - US
      confirmation:
        description: '此操作不可逆！请输入 "确认删除" 来执行。'
        required: true
        type: string

jobs:
  delete-apps:
    runs-on: ubuntu-latest
    name: 从区域 ${{ github.event.inputs.region }} 删除所有账号的应用
    
    steps:
    - name: 验证操作确认
      run: |
        if [ "${{ github.event.inputs.confirmation }}" != "确认删除" ]; then
          echo "错误：输入不匹配 '确认删除'，操作已取消。"
          exit 1
        fi

    - name: 安装 CF CLI
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install -y cf8-cli

    - name: 设置区域相关变量
      run: |
        if [ "${{ github.event.inputs.region }}" = "SG" ]; then
          echo "CF_API=https://api.cf.ap21.hana.ondemand.com" >> $GITHUB_ENV
          echo "使用新加坡(SG)区域"
        else
          echo "CF_API=https://api.cf.us10-001.hana.ondemand.com" >> $GITHUB_ENV
          echo "使用美国(US)区域"
        fi

    - name: 获取账号列表
      id: get-accounts
      run: |
        # 获取所有账号相关的变量
        accounts=()
        i=1
        while true; do
          email_var="ACCOUNT${i}_EMAIL"
          password_var="ACCOUNT${i}_PASSWORD"
          
          # 检查变量是否存在
          if [ -n "${!email_var}" ] && [ -n "${!password_var}" ]; then
            accounts+=("$i")
            echo "发现账号 $i: ${!email_var}"
            i=$((i+1))
          else
            break
          fi
        done
        
        if [ ${#accounts[@]} -eq 0 ]; then
          echo "错误：未找到任何账号配置"
          exit 1
        fi
        
        echo "找到 ${#accounts[@]} 个账号"
        echo "accounts=${accounts[*]}" >> $GITHUB_OUTPUT

    - name: 循环处理每个账号
      env:
        ACCOUNT1_EMAIL: ${{ vars.ACCOUNT1_EMAIL }}
        ACCOUNT1_PASSWORD: ${{ vars.ACCOUNT1_PASSWORD }}
        ACCOUNT2_EMAIL: ${{ vars.ACCOUNT2_EMAIL }}
        ACCOUNT2_PASSWORD: ${{ vars.ACCOUNT2_PASSWORD }}
        ACCOUNT3_EMAIL: ${{ vars.ACCOUNT3_EMAIL }}
        ACCOUNT3_PASSWORD: ${{ vars.ACCOUNT3_PASSWORD }}
        ACCOUNT4_EMAIL: ${{ vars.ACCOUNT4_EMAIL }}
        ACCOUNT4_PASSWORD: ${{ vars.ACCOUNT4_PASSWORD }}
        ACCOUNT5_EMAIL: ${{ vars.ACCOUNT5_EMAIL }}
        ACCOUNT5_PASSWORD: ${{ vars.ACCOUNT5_PASSWORD }}
      run: |
        accounts=(${{ steps.get-accounts.outputs.accounts }})
        
        for account_num in "${accounts[@]}"; do
          email_var="ACCOUNT${account_num}_EMAIL"
          password_var="ACCOUNT${account_num}_PASSWORD"
          
          email="${!email_var}"
          password="${!password_var}"
          
          echo "========================================"
          echo "开始处理账号 $account_num: $email"
          echo "========================================"
          
          # 登录并自动选择组织和空间
          cf login -a ${{ env.CF_API }} -u "$email" -p "$password" || {
            echo "错误：账号 $account_num 登录失败"
            continue
          }
          
          SELECTED_ORG=$(cf orgs | awk 'NR>3 {print $1; exit}')
          if [ -z "$SELECTED_ORG" ]; then 
            echo "警告：账号 $account_num 未找到可用组织，跳过"
            continue
          fi
          
          cf target -o "$SELECTED_ORG"
          SELECTED_SPACE=$(cf spaces | awk 'NR>3 {print $1; exit}')
          if [ -z "$SELECTED_SPACE" ]; then 
            echo "警告：账号 $account_num 未找到可用空间，跳过"
            continue
          fi
          
          cf target -s "$SELECTED_SPACE"
          echo "将从 账号$account_num / 组织: $SELECTED_ORG / 空间: $SELECTED_SPACE 中删除应用"
          
          # 获取并删除所有应用
          apps=$(cf apps | awk 'NR>3 {print $1}')
          
          if [ -z "$apps" ]; then
            echo "账号 $account_num 在区域 ${{ github.event.inputs.region }} 中未找到任何应用，无需删除。"
            continue
          fi
          
          echo "发现以下应用，将全部删除:"
          echo "$apps"
          
          # 循环删除每个应用
          for app in $apps; do
            echo "----------------------------------------"
            echo "正在删除应用: $app"
            # 使用 -f 强制删除，-r 同时删除关联的路由
            cf delete -f -r "$app" && echo "应用 $app 删除成功。" || echo "应用 $app 删除失败"
          done
          
          echo "账号 $account_num 处理完成"
          echo "----------------------------------------"
          
          # 登出当前账号
          cf logout
        done

    - name: 完成总结
      run: |
        echo "========================================"
        echo "所有账号的处理已完成"
        echo "区域: ${{ github.event.inputs.region }}"
        echo "========================================"
